version: "3.8"

services: 
    app:
        build: .
        entrypoint: /usr/local/bin/docker-php-entrypoint-dev
        command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
        volumes:
            - ./src:/var/www/app
        environment: 
            - APP_ENV=local
            - APP_KEY=base64:tLmYfUrrZITzLIkSjFnV+PCAFxkdU+duUxjVSIlrrHo=
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=host.docker.internal
            - DB_PORT=3306
            - DB_DATABASE=renedlcprofile
            - DB_USERNAME=root
            - DB_PASSWORD=
        restart: unless-stopped
        ports: 
            - 8000:80
            